### ISSUE TITLE
Selection Sort In Cpp

### ISSUE THREAD

**Issue by ST1LLWATER** [ST1LLWATER/Sorting-Algorithms#15]
- Introduction to the Sort
- Time Complexity Information Of All Scenarios
- Code For The Algorithm

**Comment by gokhalevedant06** [comment]
Hi, I would like to work on this

**Comment by anjaligoswami** [comment]
Hello, @ST1LLWATER  I would like to work on this issue.

**Comment by Karan-05** [comment]
Hi, @ST1LLWATER  I also want to work upon this

**Comment by ST1LLWATER** [comment]
Give me some time these are already in PRs ill create one for python soon so keep an eye out

**Comment by Karan-05** [comment]
Ok
