### ISSUE TITLE
Merge Sort In Cpp

### ISSUE THREAD

**Issue by ST1LLWATER** [ST1LLWATER/Sorting-Algorithms#17]
- Introduction to the Sort
- Time Complexity Information Of All Scenarios
- Code For The Algorithm

**Comment by william-monroy** [comment]
Hi @ST1LLWATER , I would like to work on this issue, can you please assign me?

**Comment by anjaligoswami** [comment]
Hello, @ST1LLWATER I would like to work on this issue.

**Comment by william-monroy** [comment]
Hi @anjaligoswami, it's a pleasure to work with you on this issue. I would like to write the code for this algorithm and if it is ok you could do the two pending points that include the explanation and the time complexity. If you need help I would be glad to help you.

**Comment by william-monroy** [comment]
I have just included the algorithm solution code in the second commit of pull request #25

**Comment by Sugam50** [comment]
Hi , I would like to work on this issue . Assign me on this issue

**Comment by william-monroy** [comment]
@ST1LLWATER I did this issue on pull request #25
