### ISSUE TITLE
Quick Sort In Cpp

### ISSUE THREAD

**Issue by ST1LLWATER** [ST1LLWATER/Sorting-Algorithms#19]
- Introduction to the Sort
- Time Complexity Information Of All Scenarios
- Code For The Algorithm

**Comment by grawish** [comment]
can I work on this issue?

**Comment by anjaligoswami** [comment]
Hello, @ST1LLWATER I would like to work on this issue.

**Comment by ajinkyabodke** [comment]
i would like to work on this issue and complete it at the earliest

**Comment by yashguptaji** [comment]
pls assign me

**Comment by ethan-x11** [comment]
I would like to work on this issue.

**Comment by SurendarSingh** [comment]
@ST1LLWATER Can I work on this Now?

**Comment by ST1LLWATER** [comment]
> @ST1LLWATER Can I work on this Now?

Umm this will be assigned to a team member raise a issue for Golang ill accept it

**Comment by SurendarSingh** [comment]
Ok @ST1LLWATER But I made the PR
if its valid, please merge 
Thank You

**Comment by SurendarSingh** [comment]
Can I raise an issue and solve it by myself ? in CPP Sorting
@ST1LLWATER

**Comment by ST1LLWATER** [comment]
Resolved
