### ISSUE TITLE
Bucket sort in c++

### ISSUE THREAD

**Issue by P-riyanka-prasad** [ST1LLWATER/Sorting-Algorithms#31]

**Comment by SugatoBagchi** [comment]
Hey, I would like to work on this. Can you please assign me?

**Comment by ajinkyabodke** [comment]
Hey, I would like to work on this. Can you please assign me?I would sumbit at the earliest

**Comment by ajinkyabodke** [comment]
@ST1LLWATER submitted the pr ,please check and merge it

**Comment by ST1LLWATER** [comment]
Resolved
