### ISSUE TITLE
Merge Sort In Golang

### ISSUE THREAD

**Issue by ST1LLWATER** [ST1LLWATER/Sorting-Algorithms#86]
- Introduction to the Sort
- Time Complexity Information Of All Scenarios
- Code For The Algorithm

**Comment by Rishi22-Coding** [comment]
I want to work on this please assign me

**Comment by rakshit234** [comment]
I would like to work on this.

**Comment by Rishi22-Coding** [comment]
@ST1LLWATER I have already opened this issue - https://github.com/ST1LLWATER/Sorting-Algorithms/pull/87#issue-1014089820
